all:
	pdflatex koen_joost_report_klein.tex
	bibtex koen_joost_report_klein
	pdflatex koen_joost_report_klein.tex
	pdflatex koen_joost_report_klein.tex

fast:
	pdflatex koen_joost_report_klein.tex

clean:
	rm -f *.toc *.aux *.out *.log *.nav *.snm *.idx